### ISSUE TITLE
Load function of CharacterFactory terminates execution with segfault

### ISSUE THREAD

**Issue by Ceyron** [Ceyron/TUMagician#2]
When creating a new character and trying to save it, I'm asked for save file name, however the input is not processed and it is just saved with the filename extension. When loading the file it terminates with a segfault, since an empty string is probably not considered.

**Comment by oguzziya** [comment]
Problem was due to the fact that there was a problem about saved character file. It is solved by adding set function for character classes. In the branch characterFactory, problem is solved.
